// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wxiwldjgxkjqdjlxgmgj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind4aXdsZGpneGtqcWRqbHhnbWdqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzU4ODA0NjksImV4cCI6MjA5MTQ1NjQ2OX0.BxPn_Y67eNHdkZxTVPAP2UciGgnWXYqan8igKX2io7Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});